puddle_store/items/urls.py
from django.urls import path
from .views import detail

app_name = 'products'

urlpatterns = [
    path('product/<slug:slug>/', detail, name='detail'),
]

puddle_store/puddle_store/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('product/',include('items.urls')),
]

puddle_store/store/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.home,name="home"),
    path('item/',views.item,name="item")
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle_store/items/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=50)
    image=models.ImageField(upload_to="photo",blank=True,null=True)
    
    
    def __str__(self):
        return self.name
class Product(models.Model):
      name=models.CharField(max_length=50)
      slug=models.SlugField(unique=True)
      image=models.ImageField(upload_to="photos",blank=True,null=True)
      description=models.TextField(blank=True,null=True)
      Category=models.ForeignKey(Category,on_delete=models.PROTECT)
      price=models.FloatField()
      stock=models.IntegerField(blank=True,null=True)
      def __str__(self):
          return self.name
      

puddle_store/store/models.py
from django.db import models

# Create your models here.

puddle_store/items/views.py
from .models import Category,Product
from django.shortcuts import render,get_object_or_404


def detail(request,slug):
    item=get_object_or_404(Product,slug=slug)
    
    return render(request,'pages/detail.html',{"item":item})

puddle_store/store/views.py
from django.shortcuts import render
from items.models import Category,Product
# Create your views here.
def home(request):
    product=Product.objects.all()
    categorie=Category.objects.all()
    context={
        'products':product,
        'categories':categorie
    }
    return render(request,'pages/home.html',context)

def item(request):
    product=Product.objects.all()
    categorie=Category.objects.all()
    context={
        'products':product,
        'categories':categorie
    }
    return render(request,'pages/category.html',context)

puddle_store/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <!--navbar header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <div class="container-fluid">
          <a class="navbar-brand" href="{%url 'home'%}">DZ COMPUTER</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a  href="{%url 'item'%}"class="nav-link active" aria-current="page" href="#">Items</a>
              </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <a><button type="button" class="btn btn-success btn-md">Sing in</button></a>
                <a><button type="button" class="btn btn-secondary btn-md">Sing up</button></a>
              </ul>
          </div>
        </div>
    </nav>
    <h1></h1>
      {% block content %}
      {% endblock content %}



      <script src={% static 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"'%}></script>
      <script src={% static "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"%}></script>
      <script src={% static "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"%}></script>

</body>
</html>

puddle_store/templates/pages/category.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="card-group">
    {% for category in categories %}
      
        <div class="card">
            <a href="#"><img src="{{category.image.url}}" class="card-img-top" alt="..." ></a>
            <div class="card-body">
              <a href="#"><h5 class="card-title">{{category.name}}</h5></a>
            </div>
          </div>
    
    {% endfor %}
</div>

{% endblock content %}

puddle_store/templates/pages/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card-group">
   
      <div class="card"  style="max-width:300px;">
        <img src="{{item.image.url}}" class="card-img-top" >
        <div class="card-body">
          <h5 class="card-title">{{item.name}}</h5>
          <p class="card-text">{{item.description}}</p>
        </div>
      </div>
 
</div>
{% endblock content %}

puddle_store/templates/pages/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="card-group">
    {% for product in products %}
      <div class="card">
        <img src="{{product.image.url}}" class="card-img-top" alt="..." >
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
        <div class="card-footer d-flex justify-content-center">
          <a href="{% url 'products:detail' product.slug %}"><button type="button" class="btn btn-outline-primary ">More info</button></a>
        </div>
      </div>
    {% endfor %}
</div>
<div class="row" id="category_bar">
  {% for category in categories  %}
  <div class="col d-flex justify-content-center">
  <a  class="fs-1 category_text" href="#">{{category.name}}</a>
  </div>
  {% endfor %}
</div >

{% endblock content %}